# .nosana-ci.yml
nosana:
  description: Build and Test Nosana Contracts

global:
  image: projectserum/build:v0.25.0
  environment:
    SOLANA_URL: devnet # testnet / devnet / mainnet / <your-custom-sol-rpc>
    PROGRAM_ID: Avrqn8UZa2EeGMHt9N7sDsxGcHTcWGYuWu8EXcyN3tv1

  # Trigger pipeline on these branches:
  trigger:
    branch:
      - nosana-ci

jobs:
  - name: install
    commands:
      - npm ci

    artifacts:
      - name: node_modules
        path: ./node_modules/

  - name: npm lint
    commands:
      - npm run eslint
      - npm run prettier
      - npm run check-types
    resources:
      - name: node_modules
        path: ./

  - name: build
    commands:
      - anchor build
    artifacts:
      - name: anchor_target
        path: ./target/

  - name: anchor test
    commands:
      - solana-keygen new --no-bip39-passphrase
      - anchor test --skip-build
    resources:
      - name: node_modules
        path: ./
      - name: anchor_target
        path: ./

  - name: rust lint
    commands:
      - cargo check --release
      - cargo test --release
      - cargo clippy --release
    resources:
      - name: anchor_target
        path: ./
