
# .nosana-ci.yml
nosana:
  description: Build and Test Nosana Contracts

global:  
  image: nosana/solana:v1.0.6
  environment:
    SOLANA_URL: devnet # testnet / devnet / mainnet / <your-custom-sol-rpc>
    PROGRAM_ID: nosJhNRqr2bc9g1nfGDcXXTXvYUmxD4cVwy2pMWhrYM
    SQUADS_AUTHORITY_PUBKEY: 9HgALjiPNoh7TbCP7h5FRUFggD1q3UjLfiU9AbTGmSGc
    SQUADS_MULTISIG_PUBKEY: 3TsTokHbDvRqsymuC5LZrK2NkUQG2LHxAShydPY2A1Cj
    SQUADS_PROGRAM_PUBKEY: GmpDbY3M5KXM9TPooZziM7SC5rT9YZZ1sf3AfTcyZwAs

  # Trigger pipeline on these branches:
  trigger:
    branch:
      - main

jobs:
#  - name: install
#    commands:
#      - npm ci
#
#    artifacts:
#      - name: node_modules
#        path: ./node_modules/

#  - name: npm lint
#    commands:
#      - npm run eslint
#      - npm run prettier
#    resources:
#      - name: node_modules
#        path: ./

  - name: build
    image: projectserum/build:v0.27.0
    commands:
      - anchor build
    artifacts:
      - name: anchor_target
        path: ./target/

#  - name: anchor test
#    commands:
#      - solana-keygen new --no-bip39-passphrase
#      - anchor test --skip-build
#    resources:
#      - name: node_modules
#        path: ./
#      - name: anchor_target
#        path: ./

#  - name: rust lint
#    commands:
#      - cargo check --release
#      - cargo test --release
#      - cargo clippy --release
#    resources:
#      - name: anchor_target
#        path: ./
  - name: solana config
    commands:
      - solana config set --url $SOLANA_URL
    artifacts:
      - name: config
        path: /root/.config
  - name: verify hash
    image: nosana/solana-verifiable-build
    commands:
      - /root/bin/solana-verify get-program-hash $PROGRAM_ID > program_hash.txt
      - /root/bin/solana-verify get-executable-hash /target/deploy/nosana_jobs.so > executable_hash.txt
      - test $(cat program_hash.txt) != $(cat executable_hash.txt) && echo 'Hashes are different, continue deploying..' || (echo 'Hashes already the same' && exit 1)
    resources:
      - name: config
        path: /
      - name: anchor_target
        path: /
        
  - name: write buffer
    secrets: 
      - SOLANA_WALLET
    commands:
      - mkdir solana
      - echo $SOLANA_WALLET > solana/private-key.json
      - solana config set --url devnet --keypair solana/private-key.json
      - solana address > solana/spill.txt
      - solana program write-buffer /helloworld.so | tee solana/buffer.txt
      - solana program set-buffer-authority "$(cut -d ' ' -f2 < solana/buffer.txt)" --new-buffer-authority $AUTHORITY_PUBKEY
    resources:
      - name: program
        path: /
    artifacts:
      - name: solana
        path: solana

  - name: squads deploy
    commands:
      - |
        nosana-cli create-program-upgrade                        \
          --name        upgradeTest                              \
          --private-key /solana/private-key.json                 \
          --buffer      "$(cut -d ' ' -f2 < /solana/buffer.txt)" \
          --spill       "$(cat /solana/spill.txt)"               \
          --multisig    $SQUADS_MULTISIG_PUBKEY                  \
          --program     $SQUADS_PROGRAM_PUBKEY                   \
          --authority   $SQUADS_AUTHORITY_PUBKEY| tee /solana/squads-deploy.json
    resources:
      - name: solana
        path: /
    artifacts:
      - name: solana
        path: /solana

  - name: wait for deploy
    commands:
      - |
        nosana-cli await-upgrade                                 \
          --private-key solana/private-key.json                  \
          --program     $SQUADS_PROGRAM_PUBKEY                   \
          --index       "$(cat solana/squads-deploy.json | tail -n 1 | jq '.upgradeIndex')"
    resources:
      - name: solana
        path: ./  